services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    # ports:
      # - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME='federico'
#      - MONGO_INITDB_ROOT_PASSWORD='m0ng0'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
#      - C:\Users\Federico\Documents\GitHub\cct_project\persistentData\mongodb:/data/db
    networks:
      - can

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - can

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      # - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: federico
      MINIO_ROOT_PASSWORD: federico
  #  volumes:
  #    - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - can
    
  decoding:
    image: decoding:1
    container_name: decoding
    restart: always
    depends_on:
      - redis
      - mongodb
    # ports:
    #   - 5000:5000
    networks:
      - can

  storeroom:
    image: storeroom-i:6
    container_name: storeroom
    restart: always
    networks:
      - can

# volumes:
#   # mongodb_data:
#   minio_data:

networks:
  can:
    driver: bridge
