services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME='federico'
#      - MONGO_INITDB_ROOT_PASSWORD='m0ng0'
#    volumes:
#      - C:\Users\Federico\Documents\GitHub\cct_project\persistentData\mongodb:/data/db
    networks:
      - can

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    #  - "9001:9001"
    volumes:
      - C:\Users\Federico\Documents\GitHub\cct_project\persistentData\mosquitto\config:/mosquitto/config
      - mosquitto_data:/persistentData/mosquitto/data
      - mosquitto_log:/persistentData/mosquitto/log
    networks:
      - can

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: federico
      MINIO_ROOT_PASSWORD: federico
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - can
    
  decoding:
    image: datadecoding-i:5
    container_name: decoding
    restart: always
    networks:
      - can

  storeroom:
    image: storeroom-i:6
    container_name: storeroom
    restart: always
    networks:
      - can

volumes:
  mongodb_data:
  minio_data:

networks:
  can:
